### ISSUE TITLE
Are community calls still happening?

### ISSUE THREAD

**Issue by Frijol** [qri-io/community#7]

**Comment by rgardaphe** [comment]
Yes! Today's was postponed, but we have one coming up on Friday 3/13. 

Here's a link to our google calendar which should have an event for each call. We have one coming up this friday at 2PM eastern - Building Qri. 

https://medium.com/qri-io/qri-community-call-calendar-91e3e0340be0

**Comment by Frijol** [comment]
oh ok! The next Using Qri is next Monday, then?

**Comment by rgardaphe** [comment]
They're both bi-weekly, so the next Using Qri is 3/23, but frankly anything you're interested in expressing/exploring is welcome on any call, so no need to wait that long. We've chosen to combine 'Building Qri' with our biweekly Sprint Demos, so that meeting is now, "here's what we built, here's what we want to build next & how"
